{% set name = "sparkmagic" %}
{% set version = "0.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/jupyter-incubator/sparkmagic/archive/{{ version }}.tar.gz"
  sha256: b1cfcb2652c589fbd2a61a56fdfa2e895a23dd21f26dd25091df98bf4c6f5a1b

build:
  number: 0
  noarch: "python"
  script: "cd sparkmagic && {{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - autovizwidget >=0.6
    - hdijupyterutils >=0.6
    - ipykernel
    - ipython >=4.0.2
    - ipywidgets >5.0.0
    - notebook >=4.2
    - numpy
    - pandas >=0.17.1
    - python
    - requests
    - requests-kerberos >=0.8.0
    - tornado >=4

test:
  imports:
    - sparkmagic

about:
  home: https://github.com/jupyter-incubator/sparkmagic
  license: BSD-3-Clause
  license_family: BSD
  summary: Jupyter magics and kernels for working with remote Spark clusters
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - danielfrg
    - itamarst
    - dbast
