{% set name = "sparkmagic" %}
{% set version = "0.12.7" %}
{% set hash_type = "sha256" %}
{% set hash_val = "874b40e4e3b9d81b89626e52a1c8ce60fd38e933c78d422440448f90fb1f0dc8" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    {{ hash_type }}: {{ hash_val }}

build:
    number: 0
    skip: true  # [win]
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
    build:
        - python
        - pip
    run:
        - python
        - notebook >=4.2
        - ipykernel >=4.2.2
        - ipywidgets >=5.0.0
        - ipython >=4.0.2
        - widgetsnbextension
        - hdijupyterutils
        - autovizwidget
        - numpy
        - pandas
        - requests
        - requests-kerberos

test:
    imports:
        - sparkmagic

about:
    home: https://github.com/jupyter-incubator/sparkmagic
    license: BSD 3-clause
    summary: Jupyter magics and kernels for working with remote Spark clusters

extra:
  recipe-maintainers:
    - danielfrg
    - itamarst
