{% set name = "sparkmagic" %}
{% set version = "0.12.9" %}
{% set hash = "2946b7199e5c4d8e6b4a48d6d8f5505f1348ea2189be4a3fdb539073a7f15691" %}

package:
  name: sparkmagic-split
  version: {{ version }}

source:
  url: "https://github.com/jupyter-incubator/sparkmagic/archive/{{ version }}.tar.gz"
  sha256: {{ hash }}

build:
  number: 2

outputs:
  - name: hdijupyterutils
    build:
      noarch: python
    script: hdijupyterutils.sh

    requirements:
      host:
        - pip
        - python
      run:
        - python
        - notebook >=4.2
        - ipykernel >=4.2.2
        - ipywidgets >=5.0.0
        - ipython >=4.0.2
        - numpy
        - pandas

    test:
      imports:
        - hdijupyterutils

  - name: autovizwidget
    build:
      noarch: python
    script: autovizwidget.sh
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - notebook >=4.2
        - ipywidgets >=5.0.0
        - plotly
        - {{ pin_subpackage('hdijupyterutils', exact=True) }}
    test:
      imports:
        - autovizwidget

  - name: sparkmagic
    script: sparkmagic.sh  # [not win]
    #script: sparkmagic.bat  # [win]

    requirements:
      host:
        - pip
        - python
      run:
        - python
        - {{ pin_subpackage('autovizwidget', exact=True) }}
        - {{ pin_subpackage('hdijupyterutils', exact=True) }}
        - ipython >=4.0.2
        - nose
        - mock
        - pandas >=0.17.1
        - numpy
        - requests
        - ipykernel
        - ipywidgets >5.0.0
        - notebook >=4.2
        - tornado >=4
        - requests-kerberos >=0.8.0

    test:
      imports:
        - sparkmagic

about:
  home: https://github.com/jupyter-incubator/sparkmagic
  license: BSD-3-Clause
  license_family: BSD
  summary: Jupyter magics and kernels for working with remote Spark clusters
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - danielfrg
    - itamarst
    - dbast
